<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="FiltroEmpresa.aspx.cs" Inherits="EjemploDataSet.FiltroEmpresa" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:SqlDataSource ID="datosEmpresas" runat="server"
                 ConnectionString="Data Source=BT318; Integrated Security=true; Initial Catalog=ejemploDB;"
                  SelectCommand="SELECT * FROM Empresa"> 
            </asp:SqlDataSource>
           <asp:SqlDataSource ID="datosEmpleados" runat="server" 
               ConnectionString="Data Source=BT318; Integrated Security=true; Initial Catalog=ejemploDB;"
               SelectCommand="SELECT * FROM Empleado"   
               FilterExpression="idEmpresa='{0}'"
                DeleteCommand="delete  from Empleado where idEmpleado=@idEmpleado" 
                UpdateCommand="update  Empleado set NombreEmpleado=? where idEmpleado=@idEmpleado"> 
                 <FilterParameters>
                    <asp:ControlParameter ControlID="desEmpresas"/>
                </FilterParameters>
            </asp:SqlDataSource>   
            <table align="center">
                <tr>
                    <td>Empresas</td>
                    <td>
                        <asp:DropDownList ID="desEmpresas" runat="server" 
                            DataSourceID="datosEmpresas" 
                            DataValueField="idEmpresa" 
                            DataTextField="NombreEmpresa" AutoPostBack="true"/>
                    </td>
                </tr>
                <tr>
                    <asp:GridView ID="Alumnos" runat="server" DataSourceID="datosEmpleados"  
                         HorizontalAlign="Center" 
                         AutoGenerateColumns="False" BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" CellPadding="2" ForeColor="Black" GridLines="None"
                         AutoGenerateEditButton="true"
                         AutoGenerateDeleteButton="true"
                         DataKeyNames="idEmpleado">
                        <AlternatingRowStyle BackColor="PaleGoldenrod"></AlternatingRowStyle>
                        <Columns>                    
                            <asp:BoundField DataField="NombreEmpleado" HeaderText="Empleado" />
                            <asp:BoundField DataField="DNI" HeaderText="DNI" />
                            <asp:BoundField DataField="Email" HeaderText="Email" />
                            <asp:BoundField DataField="Telefono" HeaderText="Telefono" /> 
                            <asp:BoundField DataField="Localidad" HeaderText="Localidad" />
                            <asp:BoundField DataField="Direccion" HeaderText="Direccion" />
                        </Columns>
                        <FooterStyle BackColor="Tan" />
                        <HeaderStyle BackColor="Tan" Font-Bold="True" />
                        <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
                        <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
                        <SortedAscendingCellStyle BackColor="#FAFAE7" />
                        <SortedAscendingHeaderStyle BackColor="#DAC09E" />
                        <SortedDescendingCellStyle BackColor="#E1DB9C" />
                        <SortedDescendingHeaderStyle BackColor="#C2A47B" />
                    </asp:GridView>
                </tr>
            </table>

        </div>
    </form>
</body>
</html>
