<%@ Page Language="C#" AutoEventWireup="true" CodeFile="GridActualizable.aspx.cs" Inherits="GridActualizable" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
     <!-- DataKeyNames para pasar la clave con la qque comparar en el where-->
    <form id="form1" runat="server">
        <div>
            <asp:AccessDataSource ID="selSector" runat="server" 
                DataSourceMode="DataReader" 
                DataFile="~/App_Data/escuela_empresa.mdb"
                SelectCommand="select * from sectores order by nom_sector"  
                DeleteCommand="delete * from sectores where cod_sector=@cod_sector" 
                UpdateCommand="update  sectores set nom_sector=? where cod_sector=@cod_sector" 
                InsertCommand="insert into sectores(cod_sector,nom_sector) values (@codigo ,@n_sector)"> 
                <InsertParameters>
                    <asp:FormParameter Name ="codigo" FormField="codigoS"/>
                    <asp:FormParameter Name ="n_sector" FormField="nombreS"/>
                </InsertParameters>
            </asp:AccessDataSource>
            <asp:GridView ID="gridSector" runat="server" DataSourceID="selSector" 
                AlternatingRowStyle-BackColor="Gainsboro" 
                HorizontalAlign="Center" 
                AutoGenerateColumns="false" 
                AutoGenerateDeleteButton="true" 
                AutoGenerateEditButton="true"
                DataKeyNames="cod_sector">
                <Columns>
                    <asp:BoundField DataField="nom_sector" HeaderText="Nombre Sector" />
                </Columns>
            </asp:GridView>
             <br/><br/>
            <center>
                <asp:TextBox ID="codigoS" runat="server" BorderWidth="0" Width="0"/>
                <asp:Label ID="Label1" runat="server" Text="Introduce el Sector: "/>
                <asp:TextBox ID="nombreS" runat="server"/>
                <br/><br/>
                <asp:Button ID="Button1" runat="server" Text="Insertar" OnClick="insercion"/>
            </center>
        </div>
    </form>
</body>
</html>
