<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Gridactualizable2.aspx.cs" Inherits="Gridactualizable2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:AccessDataSource ID="selAlunos" runat="server" 
                DataSourceMode="DataReader" 
                DataFile="~/App_Data/escuela_empresa.mdb"
                SelectCommand="select * from Alunos order by Nome"  
                DeleteCommand="delete * from Alunos where cod_aluno=@cod_aluno" 
                UpdateCommand="update  Alunos set Nome=?, nascimento=?, direccion=?, telefono1=?, cod_ins=?, cod_cidade=? where cod_aluno=@cod_aluno" 
                InsertCommand="insert into Alunos(cod_aluno, Nome, nascimento, direccion, cod_cidade, telefono1, cod_ins ) values (@codigo ,@nombre, @fechnac, @direccion, @ciudad, @telef, @insti )"> 
                <InsertParameters>
                    <asp:FormParameter Name ="codigo" FormField="codigoS"/>
                    <asp:FormParameter Name ="nombre" FormField="nombre"/>
                    <asp:FormParameter Name ="direccion" FormField="direccion"/>
                    <asp:FormParameter Name ="fechnac" FormField="fechnac"/>
                    <asp:FormParameter Name ="telef" FormField="telefono"/>
                    <asp:FormParameter Name ="ciudad" FormField="desCiudades"/>
                    <asp:FormParameter Name ="insti" FormField="desInstituto"/>
                </InsertParameters>
            </asp:AccessDataSource>
            <asp:AccessDataSource ID="selCiudades" runat="server" 
                DataSourceMode="DataReader" 
                SelectCommand="select * from Locals order by nom_local" 
                DataFile="~/App_Data/escuela_empresa.mdb"/> 
            <asp:AccessDataSource ID="selInstituto" runat="server" 
                DataSourceMode="DataReader" 
                SelectCommand="select * from Institucaos order by nom_ins" 
                DataFile="~/App_Data/escuela_empresa.mdb"/> 
            <asp:TextBox ID="codigoS" runat="server" BorderWidth="0" Width="0"/>
            <asp:table runat="server" HorizontalAlign="Center" >
                 <asp:TableRow>
                     <asp:TableCell><asp:Label ID="Label1" runat="server" Text="Nombre"/></asp:TableCell>
                     <asp:TableCell><asp:TextBox ID="nombre" runat="server"/></asp:TableCell>
                 </asp:TableRow>
                 <asp:TableRow>
                     <asp:TableCell><asp:Label ID="Label2" runat="server" Text="Direccion:"/></asp:TableCell>
                     <asp:TableCell><asp:TextBox ID="direccion" runat="server"/></asp:TableCell>
                 </asp:TableRow>
                 <asp:TableRow>
                     <asp:TableCell><asp:Label ID="Label4" runat="server" Text="Fecha nacimiento:"/></asp:TableCell>
                     <asp:TableCell><asp:TextBox ID="fechnac" runat="server"/></asp:TableCell>
                 </asp:TableRow>
                 <asp:TableRow>
                     <asp:TableCell><asp:Label ID="Label5" runat="server" Text="Telefono:"/></asp:TableCell>
                     <asp:TableCell><asp:TextBox ID="telefono" runat="server"/></asp:TableCell>
                 </asp:TableRow>
                  <asp:TableRow>
                     <asp:TableCell><asp:Label ID="Label6" runat="server" Text="Lugar Nacimiento:"/></asp:TableCell>
                     <asp:TableCell><asp:DropDownList ID="desCiudades" runat="server" 
                        DataSourceID="selCiudades" 
                        DataValueField="cod_local" 
                        DataTextField="nom_local"></asp:DropDownList></asp:TableCell>
                 </asp:TableRow>   
                 <asp:TableRow>
                     <asp:TableCell><asp:Label ID="Label7" runat="server" Text="Procedencia:"/></asp:TableCell>
                     <asp:TableCell><asp:DropDownList ID="desInstituto" runat="server" 
                        DataSourceID="selInstituto" 
                        DataValueField="cod_ins" 
                        DataTextField="nom_ins"></asp:DropDownList></asp:TableCell>
                 </asp:TableRow>  
                 <asp:TableRow>
                     <asp:TableCell RowSpan="2"><asp:Button ID="Button1" runat="server" Text="Guardar" OnClick="insercion" /></asp:TableCell>
                 </asp:TableRow>  
            </asp:table>
            <br/><br/>
            <asp:GridView ID="gridAlunos" runat="server" DataSourceID="selAlunos" 
                AlternatingRowStyle-BackColor="Gainsboro" 
                HorizontalAlign="Center" 
                AutoGenerateColumns="false" 
                AutoGenerateDeleteButton="true" 
                AutoGenerateEditButton="true"
                DataKeyNames="cod_aluno">
                <Columns>
                    <asp:BoundField DataField="Nome" HeaderText="Nombre" />
                    <asp:BoundField DataField="nascimento" HeaderText="Fecha Nacimiento" />
                    <asp:BoundField DataField="direccion" HeaderText="Direccion" />
                    <asp:BoundField DataField="telefono1" HeaderText="Telefono" />
                    <asp:BoundField DataField="cod_ins" HeaderText="Instituto" />
                    <asp:BoundField DataField="cod_cidade" HeaderText="Ciudad" />
                </Columns>
            </asp:GridView>
             <br/><br/>
        </div>
    </form>
</body>
</html>
